### ISSUE TITLE
helmfile chart with dependency is not working

### ISSUE THREAD

**Issue by tomassatka** [variantdev/chartify#12]
When using helmfile to install influxdb with transformer i bumped to following issue:

helmfile:
```
{{$namespace := "namespace-dev"}}

helmDefaults:
  createNamespace: false
  tillerless: true
  verify: false
  wait: false

releases:
  - name: influxdb
    chart: helm-virtual/influxdb
    namespace: {{$namespace}}
    transformers:
      - transformers/influxdb/route-op.yaml
      - transformers/influxdb/route-content.yaml
    values:
      - values/influxdb-values.yaml.gotmpl
```

command `helmfile -n namespace-dev sync` produce error:
```
FAILED RELEASES:NAMEinfluxdbin .helmfile/helmfile.yaml: failed processing release influxdb: command "/usr/local/bin/helm" exited with non-zero status:PATH:/usr/local/bin/helmARGS:0: helm (4 bytes)1: upgrade (7 bytes)2: --install (9 bytes)3: --reset-values (14 bytes)4: influxdb (8 bytes)5: /tmp/chartify977795748/playground-dev-influxdb-fd4f57f48/influxdb (65 bytes)6: --namespace (11 bytes)7: playground-dev (14 bytes)8: --values (8 bytes)9: /tmp/helmfile493291101/playground-dev-influxdb-values-7f57666f59 (64 bytes)10: --history-max (13 bytes)11: 10 (2 bytes)

Error: found in Chart.yaml, but missing in charts/ directory: common
```
Looks to me like dependency that is defined in Chart.yaml is not fetched:
```
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
```

The issue occurs as soon as i start to use transformers.

helmfile version:
```
user@host:~> docker run roboll/helmfile:helm3-v0.138.7 helmfile version
helmfile version v0.138.7
``` 

Offering my support here but didnt got any response on previous issues nor on PR that i raised to close one issue. Please let me know if i can help with fix.
